Update package.yml

diff --git a/.github/workflows/package.yml b/.github/workflows/package.yml
--- a/.github/workflows/package.yml
+++ b/.github/workflows/package.yml
@@ -8,11 +8,6 @@ jobs:
   update-packages:
     runs-on: ubuntu-latest
     steps:
-      - name: Self-clone
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-          token: ${{ secrets.GITHUB_TOKEN }}
       - name: Clone repository
         uses: actions/checkout@v3
         with:
@@ -22,7 +17,7 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: Setup
         uses: jirutka/setup-alpine@v1.1.3
-      - name: Install deps
+      - name: Build
         run: |
           apk add abuild abuild-rootbld findutils sed
           cd aports
@@ -30,11 +25,11 @@ jobs:
           export CBUILD=x86_64
           echo -e "\n" | abuild-keygen
           export PACKAGER_PRIVKEY=$(ls -d ~/.abuild/*.rsa | head -1)
-          sh -c "for pkg in main/* community/* testing/*; do cd $pkg; [ -e "./APKBUILD" ] && abuild -Frf >/dev/null; cd ../..;done"
+          sh -c "for pkg in main/* community/* testing/*; do cd $pkg; abuild -Frf >/dev/null 2>&1 || echo "Build ${pkg##*/} failed!"; cd ../..;done"
           mkdir -p dist
           cp -f ~/packages/*/x86_64/*.apk dist/
           cd dist/
-          apk index -vU -o APKINDEX.tar.gz *.apk
+          apk index -vU -o APKINDEX.tar.gz *.apk || true
           cd ..
         shell: alpine.sh --root {0}
       - name: Deploy
